version: 1
disable_existing_loggers: False
formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s - %(filename)s:%(lineno)d: %(message)s"
    
handlers:
  console:
    class: logging.StreamHandler
    level: INFO # INFO and above (INFO, WARNING, ERROR, CRITICAL)
    formatter: standard
    stream: ext://sys.stdout
    
  file:
    class: logging.FileHandler
    level: DEBUG # Registers all events (DEBUG, INFO, WARNING, ERROR, CRITICAL)
    formatter: standard
    filename: mcp_monitor.log
    mode: a # Append 

root:
  level: DEBUG 
  handlers: [console, file]